name: Push Event Workflow

on: push

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code
        uses : actions/checkout@v3

      - name : Install Packages
        run : pip install pytest

      - name : Run tests
        run : pytest test.py